baseURL = "/"
disableLanguages = ["fr"]
paginate = "4"
summaryLength = "10"
title = "Home | Brad Allen"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Brad Allen](https://www.bradallen.me)"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Brad Allen](https://www.bradallen.me)"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "project"
name = "projects"
weight = 3
[[menu.main]]
URL = "contact"
name = "contact"
weight = 5
[[menu.main]]
URL = "blog"
name = "blog"
weight = 4
[[menu.main]]
URL = "about"
name = "about"
weight = 2
[[menu.main]]
URL = "home"
name = "home"
weight = 1
[params]
author = "Brad Allen"
description = "Hi, I'm Brad! A Software Developer & Data Enthusiast"
google_analitycs_id = "UA-165348470-1"
logo = "images/logo.svg"
particles = true
[params.navigation_button]
enable = true
label = "contact"
link = "/#contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/particles/particles.min.js"
[[params.plugins.js]]
link = "plugins/particles/stats.min.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/mtscope"
title = "twitter"
[[params.social]]
icon = "ti-github"
link = "https://github.com/mtscope"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/mtscope"
title = "linkedin"
